import type { Metadata } from "next";
import { Open_Sans, Poppins } from "next/font/google";
import "./globals.css";
import TopHeader from "../components/shared/TopHeader";
import { Providers } from "./providers";
import { ThemeSwitch } from "@/components/shared/Switcher";

// 1. Initialize Primary Font (Open Sans)
const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

// 2. Initialize Secondary Font (Poppins)
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Electro - Electronics Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html 
      lang="en" 
      suppressHydrationWarning 
      className={`${openSans.variable} ${poppins.variable}`}
    >
      <body className="font-sans bg-background text-foreground antialiased">
        <Providers>
          <ThemeSwitch />
          <TopHeader />
          {children}
        </Providers>
      </body>
    </html>
  );
}